// components/enums/lcdas.jsx
export const lcdas = {
  'Agege': ['Agege', 'Orile-Agege'],
  'Ajeromi-Ifelodun': ['Ajeromi', 'Ifelodun'],
  'Alimosho': ['Alimosho', 'Agbado/Oke-Odo', 'Ayobo-Ipaja', 'Egbe-Idimu', 'Igando-Ikotun', 'Mosan Okunola'],
  'Amuwo-Odofin': ['Amuwo-Odofin', 'Oriade'],
  'Apapa': ['Apapa', 'Apapa Iganmu'],
  'Badagry': ['Badagry', 'Badagry West', 'Olorunda'],
  'Epe': ['Epe', 'Eredo', 'Ikosi Ejinrin'],
  'Eti-Osa': ['Eti-Osa East', 'Eti-Osa West', 'Iru/Victoria Island', 'Ikoyi-Obalende'],
  'Ibeju-Lekki': ['Ibeju', 'Lekki'],
  'Ifako-Ijaiye': ['Ifako/Ijaiye', 'Ojokoro'],
  'Ikeja': ['Ikeja', 'Ojodu', 'Onigbongbo'],
  'Ikorodu': ['Ikorodu', 'Ikorodu North', 'Ikorodu West', 'Imota', 'Ijede', 'Igbogbo-Baiyeku'],
  'Kosofe': ['Kosofe', 'Ikosi Isheri', 'Agboyi-Ketu'],
  'Lagos Island': ['Lagos Island West', 'Lagos Island East'],
  'Lagos Mainland': ['Lagos Mainland', 'Yaba'],
  'Mushin': ['Mushin', 'Odi-Olowo'],
  'Ojo': ['Ojo', 'Oto Awori', 'Iba'],
  'Shomolu': ['Shomolu', 'Bariga'],
  'Oshodi-Isolo': ['Ejigbo', 'Isolo', 'Oshodi'],
  'Surulere': ['Surulere', 'Coker Aguda', 'Itire-Ikate'],
};